/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QueryRouteImport } from './routes/query'
import { Route as PartitionsRouteImport } from './routes/partitions'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TablesTableIdRouteImport } from './routes/tables.$tableId'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const PartitionsRoute = PartitionsRouteImport.update({
  id: '/partitions',
  path: '/partitions',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesTableIdRoute = TablesTableIdRouteImport.update({
  id: '/$tableId',
  path: '/$tableId',
  getParentRoute: () => TablesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/metrics': typeof MetricsRoute
  '/partitions': typeof PartitionsRoute
  '/query': typeof QueryRoute
  '/settings': typeof SettingsRoute
  '/snapshots': typeof SnapshotsRoute
  '/tables': typeof TablesRouteWithChildren
  '/tables/$tableId': typeof TablesTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/metrics': typeof MetricsRoute
  '/partitions': typeof PartitionsRoute
  '/query': typeof QueryRoute
  '/settings': typeof SettingsRoute
  '/snapshots': typeof SnapshotsRoute
  '/tables': typeof TablesRouteWithChildren
  '/tables/$tableId': typeof TablesTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/metrics': typeof MetricsRoute
  '/partitions': typeof PartitionsRoute
  '/query': typeof QueryRoute
  '/settings': typeof SettingsRoute
  '/snapshots': typeof SnapshotsRoute
  '/tables': typeof TablesRouteWithChildren
  '/tables/$tableId': typeof TablesTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connections'
    | '/dashboard'
    | '/help'
    | '/metrics'
    | '/partitions'
    | '/query'
    | '/settings'
    | '/snapshots'
    | '/tables'
    | '/tables/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connections'
    | '/dashboard'
    | '/help'
    | '/metrics'
    | '/partitions'
    | '/query'
    | '/settings'
    | '/snapshots'
    | '/tables'
    | '/tables/$tableId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/connections'
    | '/dashboard'
    | '/help'
    | '/metrics'
    | '/partitions'
    | '/query'
    | '/settings'
    | '/snapshots'
    | '/tables'
    | '/tables/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  MetricsRoute: typeof MetricsRoute
  PartitionsRoute: typeof PartitionsRoute
  QueryRoute: typeof QueryRoute
  SettingsRoute: typeof SettingsRoute
  SnapshotsRoute: typeof SnapshotsRoute
  TablesRoute: typeof TablesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partitions': {
      id: '/partitions'
      path: '/partitions'
      fullPath: '/partitions'
      preLoaderRoute: typeof PartitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$tableId': {
      id: '/tables/$tableId'
      path: '/$tableId'
      fullPath: '/tables/$tableId'
      preLoaderRoute: typeof TablesTableIdRouteImport
      parentRoute: typeof TablesRoute
    }
  }
}

interface TablesRouteChildren {
  TablesTableIdRoute: typeof TablesTableIdRoute
}

const TablesRouteChildren: TablesRouteChildren = {
  TablesTableIdRoute: TablesTableIdRoute,
}

const TablesRouteWithChildren =
  TablesRoute._addFileChildren(TablesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConnectionsRoute: ConnectionsRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  MetricsRoute: MetricsRoute,
  PartitionsRoute: PartitionsRoute,
  QueryRoute: QueryRoute,
  SettingsRoute: SettingsRoute,
  SnapshotsRoute: SnapshotsRoute,
  TablesRoute: TablesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
