import type { MetaTable } from "./mock-data";

// ─── SQL DDL ────────────────────────────────────────────────────────────────
export function exportToSQL(table: MetaTable): string {
  const cols = table.schema
    .map((c) => {
      const type = toSQLType(c.type);
      const nullable = c.nullable ? "" : " NOT NULL";
      return `  ${c.name.padEnd(24)} ${type}${nullable}`;
    })
    .join(",\n");

  const partitionKeys = table.schema.filter((c) => c.partition).map((c) => c.name);
  const partitionClause =
    partitionKeys.length > 0
      ? `\nPARTITIONED BY (${partitionKeys.join(", ")})`
      : "";

  const formatComment = `-- Format: ${table.format}\n-- Location: ${table.location}\n-- Generated by NexaGlint\n\n`;

  return `${formatComment}CREATE TABLE IF NOT EXISTS ${table.name} (\n${cols}\n)${partitionClause};`;
}

function toSQLType(type: string): string {
  const t = type.toLowerCase();
  if (t === "string" || t === "varchar") return "VARCHAR";
  if (t === "date") return "DATE";
  if (t === "timestamp") return "TIMESTAMP";
  if (t === "boolean") return "BOOLEAN";
  if (t === "int" || t === "integer") return "INT";
  if (t === "long" || t === "bigint") return "BIGINT";
  if (t === "float") return "FLOAT";
  if (t === "double") return "DOUBLE";
  if (t.startsWith("decimal")) return t.toUpperCase();
  if (t.startsWith("map<")) return "MAP";
  if (t.startsWith("array<")) return "ARRAY";
  return type.toUpperCase();
}

// ─── JSON Schema ─────────────────────────────────────────────────────────────
export function exportToJSONSchema(table: MetaTable): string {
  const properties: Record<string, object> = {};
  const required: string[] = [];

  table.schema.forEach((c) => {
    properties[c.name] = {
      type: toJSONSchemaType(c.type),
      description: c.partition ? `Partition key — ${c.type}` : c.type,
    };
    if (!c.nullable) required.push(c.name);
  });

  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: table.name,
    description: `Schema for ${table.name} (${table.format}) — Generated by NexaGlint`,
    type: "object",
    properties,
    required,
  };

  return JSON.stringify(schema, null, 2);
}

function toJSONSchemaType(type: string): string {
  const t = type.toLowerCase();
  if (t === "string" || t === "varchar" || t.startsWith("map") || t.startsWith("array")) return "string";
  if (t === "boolean") return "boolean";
  if (t === "int" || t === "integer" || t === "long" || t === "bigint") return "integer";
  if (t === "float" || t === "double" || t.startsWith("decimal")) return "number";
  if (t === "date" || t === "timestamp") return "string";
  return "string";
}

// ─── Avro Schema ─────────────────────────────────────────────────────────────
export function exportToAvro(table: MetaTable): string {
  const fields = table.schema.map((c) => ({
    name: c.name,
    type: c.nullable ? ["null", toAvroType(c.type)] : toAvroType(c.type),
    doc: c.partition ? `Partition key` : undefined,
  }));

  const schema = {
    type: "record",
    name: table.name,
    namespace: "com.nexaglint.schema",
    doc: `${table.format} table at ${table.location} — Generated by NexaGlint`,
    fields,
  };

  return JSON.stringify(schema, null, 2);
}

function toAvroType(type: string): string {
  const t = type.toLowerCase();
  if (t === "string" || t === "varchar") return "string";
  if (t === "boolean") return "boolean";
  if (t === "int" || t === "integer") return "int";
  if (t === "long" || t === "bigint") return "long";
  if (t === "float") return "float";
  if (t === "double") return "double";
  if (t.startsWith("decimal")) return "string"; // Avro uses string for decimals
  if (t === "date") return "string";
  if (t === "timestamp") return "string";
  if (t.startsWith("map<")) return "string";
  if (t.startsWith("array<")) return "string";
  return "string";
}

// ─── dbt Model ───────────────────────────────────────────────────────────────
export function exportToDbt(table: MetaTable): string {
  const colDocs = table.schema
    .map((c) => `        ${c.name}:\n          description: "${c.partition ? "[Partition Key] " : ""}${c.type}${c.nullable ? "" : " (required)"}"`)
    .join("\n");

  const partitionKeys = table.schema.filter((c) => c.partition).map((c) => c.name);

  const yamlBlock = `# models/${table.name}.yml
# Generated by NexaGlint

version: 2

models:
  - name: ${table.name}
    description: "${table.format} table located at ${table.location}"
    config:
      materialized: incremental${partitionKeys.length > 0 ? `\n      partition_by:\n        field: ${partitionKeys[0]}\n        data_type: date` : ""}
    columns:
${colDocs}
`;

  const sqlBlock = `-- models/${table.name}.sql
-- Generated by NexaGlint

{{
  config(
    materialized='incremental',
    unique_key='${table.schema[0]?.name ?? "id"}'
  )
}}

SELECT
${table.schema.map((c) => `  ${c.name}`).join(",\n")}
FROM {{ source('lakehouse', '${table.name}') }}

{% if is_incremental() %}
WHERE ${partitionKeys[0] ?? table.schema[0]?.name} > (SELECT MAX(${partitionKeys[0] ?? table.schema[0]?.name}) FROM {{ this }})
{% endif %}
`;

  return `${yamlBlock}\n\n${sqlBlock}`;
}

// ─── Download helper ──────────────────────────────────────────────────────────
export function downloadFile(content: string, filename: string, mimeType = "text/plain") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
